/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "eu-north-1",
    endpoint: "https://i7mizte33k.execute-api.eu-north-1.amazonaws.com/prod",
};


export default awsmobile;
